### PR TITLE
Fix type mismatch diagnostic for types in a double negative position

### LINKED ISSUE #1335: Error message for type mismatch in a double negative position is confusing
## Example
In this example, `Foo` expects an operation of type `Int => Unit`. If you give it an operation of type `Bool => Unit`, where the mismatch occurs in a double negative (i.e. positive) position, then the error message shows the "expected" and "actual" types in the opposite way you would expect.

```qsharp
@EntryPoint()
operation Main() : Unit {
    Foo(Bar);
}

operation Foo(op : Int => Unit) : Unit {}

operation Bar(x : Bool) : Unit {}
```

```
The type Int does not match the type Bool.
Actual type:   (Int => Unit)
Expected type: (Bool => Unit)
```

This is different than when the type mismatch occurs in a negative position, e.g. `Foo("bar")`, where `Int => Unit` is now the "expected" type.

```
The type String does not match the type (Int => Unit).
Actual type:   String
Expected type: (Int => Unit)
```

## Expected behavior

The error message should better match the context of the call expression, i.e. the expected type should probably always be the parameter type specified by `Foo`. The error message should still communicate the direction of the variance somehow.

There is also a bug in the diagnostic range: it appears on the first character of the statement instead of on the argument.

### PR DESCRIPTION
**Pull request by samarsha**
* Add the direction of subtyping to the internal type inference API. The left-hand side is the expected type in error messages. Flip only the direction of subtyping when entering a negative position, rather than swapping the LHS and RHS. This fixes #1335.
* Refactor the way diagnostics are generated by the type inference module. Propagate context information bottom-up rather than top-down, which simplifies the private type inference API.

### CODE REVIEW

File: src/QsCompiler/SyntaxProcessor/TypeInference/InferenceContext.fs [hunk 1]
```diff
@@ -20,100 +20,143 @@ open Microsoft.Quantum.QsCompiler.Transformations.QsCodeOutput
...
+    | TypeMismatch of TypeMismatch
+    | TypeIntersectionMismatch of ordering: Ordering * mismatch: TypeMismatch
+    | CompilerDiagnostic of QsCompilerDiagnostic
+
+module Diagnostic =
+    let withContext expected (actual: ResolvedType) =
+        let sameRange (type_: ResolvedType) : ResolvedType option -> _ =
+            Option.forall (fun context -> type_.Range = context.Range)
+
+        function
```
Comment (ScottCarda-MS) [inline src/QsCompiler/SyntaxProcessor/TypeInference/InferenceContext.fs:99]: What argument is being matched here?

File: src/QsCompiler/SyntaxProcessor/TypeInference/InferenceContext.fs [hunk 2]
```diff
@@ -20,100 +20,143 @@ open Microsoft.Quantum.QsCompiler.Transformations.QsCodeOutput
...
+        | TypeMismatch mismatch ->
+            if sameRange actual mismatch.ActualContext then
```
Comment (ScottCarda-MS) [inline src/QsCompiler/SyntaxProcessor/TypeInference/InferenceContext.fs:101]: I don't understand this line. If the Diagnostic already has a context, then withContext is supposed to replace it, right? Here it seems, if the range of the existing context is the same as the range for the desired context, it gets replaced, or if there isn't an existing context, it gets replaced. But if a context already exists and has a different range, than NoOp?

File: src/QsCompiler/SyntaxProcessor/TypeInference/InferenceContext.fs [hunk 3]
```diff
@@ -20,100 +20,143 @@ open Microsoft.Quantum.QsCompiler.Transformations.QsCodeOutput
...
-        /// The most recent relevant ancestor of the right-hand type.
-        OriginalRight: ResolvedType
+    let (.>) lhs rhs = Relation(lhs, Supertype, rhs)
+
+type TypeMismatch =
+    {
+        Expected: ResolvedType
+        ExpectedContext: ResolvedType option
+        Actual: ResolvedType
+        ActualContext: ResolvedType option
```
Comment (ScottCarda-MS) [inline src/QsCompiler/SyntaxProcessor/TypeInference/InferenceContext.fs:74]: Some comments here explaining the fields, especially the context fields, would be helpful. I'm not yet understanding what the context fields are used for.

File: src/QsCompiler/SyntaxProcessor/TypeInference/InferenceContext.fs [hunk 4]
```diff
@@ -20,100 +20,143 @@ open Microsoft.Quantum.QsCompiler.Transformations.QsCodeOutput
...
+            Option.forall (fun context -> type_.Range = context.Range)
+
+        function
+        | TypeMismatch mismatch ->
+            if sameRange actual mismatch.ActualContext then
+                mismatch |> TypeMismatch.withContext expected actual |> TypeMismatch
+            else
+                TypeMismatch mismatch
+        | TypeIntersectionMismatch (ordering, mismatch) ->
+            if sameRange expected mismatch.ExpectedContext && sameRange actual mismatch.ActualContext then
```
Comment (ScottCarda-MS) [inline src/QsCompiler/SyntaxProcessor/TypeInference/InferenceContext.fs:106]: Is there a reason we do sameRange for both the expected and the actual contexts here, where in the TypeMismatch case we only check the actual context?

File: src/QsCompiler/DataStructures/Diagnostics.fs [hunk 5]
```diff
@@ -465,10 +465,9 @@ type DiagnosticItem =
     static member Message(code: ErrorCode, args: IEnumerable<string>) =
         let message =
             match code with
-            | ErrorCode.TypeMismatch ->
-                "The type {1} does not match the type {0}.\nActual type:   {3}\nExpected type: {2}"
+            | ErrorCode.TypeMismatch -> "The type {0} does not match the type {1}.\nExpected: {2}\n  Actual: {3}"
```
Comment (ScottCarda-MS) [inline src/QsCompiler/DataStructures/Diagnostics.fs:468]: Does this make TypeMismatch a special case of the TypeIntersectionMismatch, where the first argument is 'match'?

**Review by ScottCarda-MS — APPROVED** [review]

File: src/QsCompiler/SyntaxProcessor/TypeInference/InferenceContext.fs (hunk 1 above)
Comment (samarsha) [reply src/QsCompiler/SyntaxProcessor/TypeInference/InferenceContext.fs]: The third argument of `withParents`, which is a `Diagnostic`.

File: src/QsCompiler/SyntaxProcessor/TypeInference/InferenceContext.fs (hunk 2 above)
Comment (samarsha) [reply src/QsCompiler/SyntaxProcessor/TypeInference/InferenceContext.fs]: The range checking is designed to find the type of the expression underlined by the diagnostic, and stop updating the parent types after that point. I added a doc comment to `Diagnostic.withParents` about this.

File: src/QsCompiler/SyntaxProcessor/TypeInference/InferenceContext.fs (hunk 3 above)
Comment (samarsha) [reply src/QsCompiler/SyntaxProcessor/TypeInference/InferenceContext.fs]: I renamed this type and its fields to hopefully be clearer, and I added a doc comment with an example. The new type name is `TypeContext`.

File: src/QsCompiler/SyntaxProcessor/TypeInference/InferenceContext.fs (hunk 4 above)
Comment (samarsha) [reply src/QsCompiler/SyntaxProcessor/TypeInference/InferenceContext.fs]: It depends on whether the range of the actual type, or the ranges of both the expected and actual types, are used to create the compiler diagnostic in `Diagnostic.toCompilerDiagnostic`. I added a comment here to explain that.

File: src/QsCompiler/SyntaxProcessor/TypeInference/InferenceContext.fs [hunk 6]
```diff
@@ -20,100 +20,143 @@ open Microsoft.Quantum.QsCompiler.Transformations.QsCodeOutput
...
+
+    let private typeMismatchArgs mismatch =
+        let expectedContext = mismatch.ExpectedContext |> Option.defaultValue mismatch.Expected
+        let actualContext = mismatch.ActualContext |> Option.defaultValue mismatch.Actual
+
+        [
+            describeType mismatch.Actual
+            describeType mismatch.Expected
+            SyntaxTreeToQsharp.Default.ToCode expectedContext
+            SyntaxTreeToQsharp.Default.ToCode actualContext
```
[the remark this answers is not in the document]
Comment (samarsha) [reply src/QsCompiler/SyntaxProcessor/TypeInference/InferenceContext.fs]: `describeType` is the same as `SyntaxTreeToQsharp.Default.ToCode`, except it adds extra info if the type is a type parameter. The extra info is designed to fit into the first parent of the error message, but not the second part (which has the parents/context). Example:

```
Couldn't match type parameter 'a (bound by Foo) with type Qubit.
Expected: Qubit
  Actual: 'a
```

"Actual: parameter 'a (bound by Foo)" would look weird. (I agree that this is kind of confusing and a fragile part of the diagnostic message generation, though.)

File: src/QsCompiler/DataStructures/Diagnostics.fs (hunk 5 above)
Comment (samarsha) [reply src/QsCompiler/DataStructures/Diagnostics.fs]: Sort of, but they don't quite mean the same thing by "expected type"... for TypeMismatch, the actual type is usually a subtype of the expected type. For TypeIntersectionMismatch, the actual type may be either a subtype or a supertype of the expected type. I changed the error messages a bit based on this.

File: src/QsCompiler/DataStructures/Diagnostics.fs [hunk 7]
```diff
@@ -465,23 +465,24 @@ type DiagnosticItem =
...
         | _ -> str // let's fail silently for now
 
-    static member Message(code: ErrorCode, args: IEnumerable<string>) =
-        let unlines = String.concat Environment.NewLine
+    static member Message(code, args) =
+        let typeMismatch summary expected actual =
+            String.concat Environment.NewLine [ summary; "Expected: " + expected; "  Actual: " + actual ]
 
         let message =
             match code with
```
Comment (ScottCarda-MS) [inline src/QsCompiler/DataStructures/Diagnostics.fs:473]: The numbering for the arguments in these error messages seems pretty out of order. Is this does to maintain consistency with how these error codes would have been pass arguments before?

Comment (samarsha) [reply src/QsCompiler/DataStructures/Diagnostics.fs:473]: I wanted to use the same function `Diagnostic.typeContextArgs` to create the argument list for all the type errors, and let each error message decide the best order to display them in. Unfortunately it does look pretty confusing with the argument numbers - this would be cleaner if #1025 was resolved and each diagnostic argument had a name instead of a number.
