### PR TITLE
Fixed Issue with Range Slicing Bug

### LINKED ISSUE #1430: Open ended array slices are running into a type inference issue
The following code results in a compiler exception from [this location](https://github.com/microsoft/qsharp-compiler/blob/f92292d6892132378cabbbb0c5113f39c76a1b1d/src/QsCompiler/Core/SyntaxGenerator.fs#L332).

```qsharp
        let arr1 = [1,2,3];
        let arr2 = [6, size = 3];

        let concatenated = arr1 + arr2;
        let slice = concatenated[arr1[0]..arr1[1]...];
```
A similar issue may exist for other open ended ranges (as part of slicing or as part of copy-and-update).

Edit: Capturing another case that seems to silently fail here since it is also an issue with open ended ranges; this may or may not be the same/a similar issue. This is the case that throws during building the compilation:
```qsharp
    operation LengthCaching (vals : Int[]) : Int[] {
        return vals[...vals[0]...];
    }
```

### PR DESCRIPTION
**Pull request by ScottCarda-MS**
Fixes #1430

### CODE REVIEW

File: src/QsCompiler/SyntaxProcessor/ExpressionVerification.fs [hunk 1]
```diff
@@ -434,13 +434,15 @@ type QsExpression with
             let openStartInSlicing =
                 function
                 | Some step when Some step |> validSlicing ->
-                    conditionalIntExpr (IsNegative step) (LengthMinusOne array) (SyntaxGenerator.IntLiteral 0L)
+                    let inferredStep = { step with ResolvedType = Int |> ResolvedType.New } // validSlicing ensures that the type must be an Int
```
Comment (samarsha) [inline src/QsCompiler/SyntaxProcessor/ExpressionVerification.fs:437]: I would recommend moving the call to `inference.Resolve` out of `validSlicing` and instead have `integerExpr` return:

```fsharp
{ ex with ResolvedType = inference.Resolve ex.ResolvedType }
```

Then `validSlicing`, `openStartInSlicing`, and `openEndInSlicing` don't need to worry about resolving the type.

Comment (ScottCarda-MS) [reply src/QsCompiler/SyntaxProcessor/ExpressionVerification.fs]: I'm not sure what all that line affects, so let me know if it can be removed or not, please.

File: src/QsCompiler/SyntaxProcessor/ExpressionVerification.fs [hunk 2]
```diff
@@ -446,8 +445,7 @@ type QsExpression with
             let resolveSlicingRange start step end_ =
                 let integerExpr ex =
                     let ex = resolve context ex
-                    inference.Constrain(ResolvedType.New Int .> ex.ResolvedType) |> List.iter diagnose
-                    ex
+                    { ex with ResolvedType = inference.Resolve ex.ResolvedType }
```
Comment (samarsha) [inline src/QsCompiler/SyntaxProcessor/ExpressionVerification.fs:448]: Can you rename this function since it isn't related to integers anymore?

Comment (ScottCarda-MS) [reply src/QsCompiler/SyntaxProcessor/ExpressionVerification.fs]: Oh yah I guess this function's purpose changed. Renamed to `toResolvedExpr`.

**Review by samarsha — APPROVED** [review]
